name: lab_test_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.5+16

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  sizer: ^2.0.15
  flutter_screenutil: ^5.9.0
  flutter_svg: ^1.1.2

  shared_preferences: ^2.0.15
  convex_bottom_bar: ^3.0.0
  figma_squircle: ^0.5.3
  syncfusion_flutter_datepicker: ^25.1.40
  percent_indicator: ^4.2.2
  url_launcher: ^6.1.5
#  http: ^0.13.6
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  flutter_rating_bar: ^4.0.1

  #paytment
  flutter_cashfree_pg_sdk: ^2.0.12+15

  #map
  google_maps_flutter: ^2.6.0
  location: ^5.0.3
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  google_map_polyline_new: ^0.3.0+2

  carousel_slider: ^4.2.1
  file_picker: ^5.3.00
  intl: any

  #networking
  flutter_html: ^3.0.0-alpha.3
  flutter_widget_from_html: ^0.9.1
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  mime: ^1.0.4
  readmore: ^2.1.0
  connectivity_plus: ^4.0.1
  http_parser: ^4.0.2

  #socket
  socket_io_client: ^2.0.3+1

  permission_handler: ^10.2.0

  #firebase
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.1
  firebase_messaging: ^14.6.2
  gap: ^3.0.1

  uuid: ^3.0.7

  #  flutter_animation_progress_bar: ^2.2.1
  flutter_time_picker_spinner: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  share_plus: ^7.0.2
  timer_count_down: ^2.2.2
  html: ^0.15.4
  maps_launcher: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500

flutter_launcher_icons:
  ios: true
  android: 'ic_launcher'
  image_path_ios: "assets/images/logo.png"
  image_path_android: "assets/images/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff" # used only for android

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
